### ISSUE TITLE
Calls to the WebAPI return a 500 error code with exception SEVERE: Allocate exception for servlet [org.ohdsi.webapi.JerseyConfig]

### ISSUE THREAD

**Issue by chgl** [OHDSI/WebAPI#1815]
### Expected behavior

Calls to the WebAPI's endpoints should return a successful response.

### Actual behavior

Starting with version 2.8.1, any call to the WebAPI fails with status code `500` and the following logs:

```console
webapi_1  | Mar 13, 2021 9:42:12 PM org.apache.catalina.core.StandardWrapperValve invoke
webapi_1  | SEVERE: Allocate exception for servlet [org.ohdsi.webapi.JerseyConfig]
webapi_1  | java.lang.IllegalArgumentException
webapi_1  |     at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:171)
webapi_1  |     at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
webapi_1  |     at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:425)
webapi_1  |     at org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener.process(AnnotationAcceptingListener.java:170)
webapi_1  |     at org.glassfish.jersey.server.ResourceConfig.scanClasses(ResourceConfig.java:915)
webapi_1  |     at org.glassfish.jersey.server.ResourceConfig._getClasses(ResourceConfig.java:869)
webapi_1  |     at org.glassfish.jersey.server.ResourceConfig.getClasses(ResourceConfig.java:775)
webapi_1  |     at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1206)
webapi_1  |     at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1178)
webapi_1  |     at org.glassfish.jersey.server.ResourceConfig.createRuntimeConfig(ResourceConfig.java:1174)
webapi_1  |     at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:345)
webapi_1  |     at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392)
webapi_1  |     at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177)
webapi_1  |     at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369)
webapi_1  |     at javax.servlet.GenericServlet.init(GenericServlet.java:244)
webapi_1  |     at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1132)
webapi_1  |     at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:779)
webapi_1  |     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:134)
webapi_1  |     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
webapi_1  |     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
webapi_1  |     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
webapi_1  |     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
webapi_1  |     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
webapi_1  |     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
webapi_1  |     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
webapi_1  |     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
webapi_1  |     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
webapi_1  |     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
webapi_1  |     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
webapi_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
webapi_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
webapi_1  |     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
webapi_1  |     at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to reproduce behavior

1. Create the following `docker-compose.yaml`:

```yaml
# basically created from the Helm chart at https://github.com/chgl/charts/tree/master/charts/ohdsi
services:
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ohdsi
  webapi:
    image: ohdsi/webapi:2.8.1
    ports:
      - 9999:8080
    environment:
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_URL: jdbc:postgresql://db:5432/ohdsi
      DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_PASSWORD: postgres
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://db:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi
      SECURITY_CORS_ENABLED: "false"
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
```

1. Run `docker-compose up`

1. Run `curl http://localhost:9999/WebAPI/info` and get a 500 error.
