### ISSUE TITLE
Maven settings file is not imported correctly in Docker build

### ISSUE THREAD

**Issue by gutte** [OHDSI/WebAPI#2049]
### Expected behavior

Maven settings file `WebAPIConfig/settings.xml` should be used when building using the Dockerfile.

### Actual behavior

The settings are not included.

### Steps to reproduce behavior

`docker build -t webapi .`

**Comment by chgl** [comment]
Most if not all of the parameters can also be set using environment variables. For example, if you're using docker-compose:

```yaml
services:
  ohdsi-webapi:
    image: docker.io/ohdsi/webapi:2.11.1@sha256:9bcb5003e6504669b53c94f3e0b4aa6ad9b5c78741f772ca402579632ce64fb3
    environment:
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://ohdsi-omop-db:5432/ohdsi
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://ohdsi-omop-db:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_PASSWORD: postgres
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi
      SECURITY_CORS_ENABLED: "true"
      SECURITY_ORIGIN: "http://ohdsi.127.0.0.1.nip.io"
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 4096m
    read_only: true
    tmpfs:
      - /tmp
    privileged: false
```

Here's a complete docker-compose example including traefik+atlas+postgres:

<details>
  <summary>Click to expand!</summary>
```yaml
services:
  traefik:
    image: docker.io/library/traefik:v2.8.0@sha256:e2ba68ab66797f6a89b49e389d9d77bfd7118bd07f17daa2042c03861d8d2ace
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    read_only: true
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      resources:
        limits:
          memory: 128m

  ohdsi-omop-db:
    image: docker.io/library/postgres:14.4@sha256:4ba3b78788bb284687376b9c1e0565b245375ddee0fe14cef25e315b6bd88b1a
    restart: unless-stopped
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    shm_size: 1024m
    privileged: false
    deploy:
      resources:
        limits:
          memory: 2048m
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ohdsi

  ohdsi-webapi:
    image: docker.io/ohdsi/webapi:2.11.1@sha256:9bcb5003e6504669b53c94f3e0b4aa6ad9b5c78741f772ca402579632ce64fb3
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 4096m
    read_only: true
    tmpfs:
      - /tmp
    privileged: false
    environment:
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://ohdsi-omop-db:5432/ohdsi
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://ohdsi-omop-db:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_PASSWORD: postgres
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi
      SECURITY_CORS_ENABLED: "true"
      SECURITY_ORIGIN: "http://ohdsi.127.0.0.1.nip.io"
    depends_on:
      - ohdsi-omop-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ohdsi-webapi.rule=Host(`ohdsi.127.0.0.1.nip.io`) && PathPrefix(`/WebAPI`)"
      - "traefik.http.routers.ohdsi-webapi.entrypoints=web"

  ohdsi-atlas:
    image: docker.io/ohdsi/atlas:2.11.1@sha256:36df31ecd1c92f2f2d66535ff759e7626545179696a3f291f35dc75c14017564
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 64m
          cpus: "1"
    privileged: false
    environment:
      WEBAPI_URL: "http://ohdsi.127.0.0.1.nip.io/WebAPI"
    depends_on:
      - ohdsi-webapi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ohdsi-atlas.rule=Host(`ohdsi.127.0.0.1.nip.io`) && PathPrefix(`/atlas`)"
      - "traefik.http.routers.ohdsi-atlas.entrypoints=web"

```
</details>
